dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
sudo: false
before_install: gem install bundler
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
