dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
before_install:
  - ./test/ci/install_libsodium.sh
  - export LD_LIBRARY_PATH=$HOME/libsodium/lib:$LD_LIBRARY_PATH
cache:
  directories:
    - $HOME/libsodium
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
