dist: xenial
language: ruby
rvm: 2.5.3
gemfile:
  - Gemfile
  - test/gemfiles/activerecord51.gemfile
  - test/gemfiles/activerecord50.gemfile
  - test/gemfiles/activerecord42.gemfile
before_install: ./test/ci/before_install.sh
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
cache:
  directories:
    - $HOME/libsodium
